name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  # path: ^1.9.0

dev_dependencies:
  analysis_defaults:
    path: ../../analysis_defaults
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  lints: ^6.0.0
  test: ^1.25.6
