name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shared:
    path: ../shared
dev_dependencies:
  analysis_defaults:
    path: ../../analysis_defaults
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.25.6
